version: '3.9'

services:
  database_coluna_reta:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database_coluna_reta
    restart: always
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
  app:
    build: .
    container_name: coluna_reta
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database_coluna_reta

    depends_on:
      - database_coluna_reta

volumes:
  pgdata:
    driver: local
