name: Renovate
on:
  schedule:
    - cron: '7 5 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/renovate@37.55.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
