name: Renovate
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/renovate@27.23.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
